### ISSUE TITLE
About the data source

### ISSUE THREAD

**Issue by Statisticss** [EagleW/Contextualized-Literature-based-Discovery#1]
Thank you for this great work!
I have a question about the data source. How did you get the data (kg, ct, e2t files in the /data folder)? Did you download them from somewhere? Or did you do some preprocess to get them? You mentioned that you have used algorithms like PL-marker, but I didn't find them in the repo. Am I missing something here?

**Comment by EagleW** [comment]
Hi @Statisticss , Thank you for your interest in our research. We did not include the preprocessing code in the repository. The preprocessing steps are in [paper](https://arxiv.org/pdf/2305.14259.pdf ), page 13, appendix A. All the preprocessing code can be downloaded from their GitHub links. For example, PL-marker is on [this page](https://github.com/thunlp/PL-Marker). Please feel free to post if you have other questions.

**Comment by Statisticss** [comment]
Got it! Thanks for your quick reply!
