### ISSUE TITLE
How did you obtain the raw data?

### ISSUE THREAD

**Issue by oyarsa** [EagleW/Contextualized-Literature-based-Discovery#2]
The repository and the README instructions refer to your pre-processed files from the original corpus of papers. Would it be possible to describe how you arrived at those files? I want to use the ACL subset of S2ORC, and it would be great if you could share how you obtained and processed it.

**Comment by oyarsa** [comment]
Sorry, I only saw the other issue answering this very question after I opened this.

**Comment by oyarsa** [comment]
Never mind, I'm reopening this. The paper and the previous issue don't describe how you got the papers. You mentioned you got them from the Semantic Scholar API, but did you filter them only for the ACL Anthology papers? What endpoint did you use? Can you share the query?

**Comment by EagleW** [comment]
Hi @oyarsa Thank you very much for your interest in our research. Unfortunately, we used an internal API by AI2, which probably cannot match the semantic scholar API. We only choose the ACL papers in our paper based on source field from AWS database . Our crawled papers only have title and abstracts. I think you can ask in Semantic Scholar API Slack for more detailed information.

**Comment by oyarsa** [comment]
Thanks for the prompt response! I'll reach out to Semantic Scholar for further help in this.

**Comment by EagleW** [comment]
Good luck!
